version: "3.9"

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.2
    ports:
      - 9200:9200
 
  kibana:
    container_name: kibana
    image: kibana:8.12.2
    ports:
      - 5601:5601

  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    ports:
      - 29092:29092
    
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
      
  mongo:
    container_name: mongo
    image: mongo:5.0
    ports:
      - 27017:27017

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9090:9090
      - 9000:9000
 
  minio_mc_init:
    image: minio/mc
    container_name: minio_mc_init

  redis:
    container_name: redis
    image: redis:7.2.4
    ports:
      - 6379:6379
    
  identity:  
    container_name: identity
    build:
      context: .
      dockerfile: "Identity/Dockerfile"
    ports:
      - 8081:7031
      - 8181:8031

  musicservice:
    container_name: musicservice
    build:
      context: .
      dockerfile: "MusicService/Dockerfile"
    ports:
      - 8082:7127

  subscriptionservice:
    container_name: subscriptionservice
    build:
      context: .
      dockerfile: "SubscriptionService/Dockerfile"
    ports:
      - 8083:7060